<a href="https://colab.research.google.com/github/hatkiet/deep-learning-challenge/blob/main/AlphabetSoupCharity_Optimization_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
application_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EIN                     34299 non-null  int64
 1   NAME                    34299 non-null  object
 2   APPLICATION_TYPE        34299 non-null  object
 3   AFFILIATION             34299 non-null  object
 4   CLASSIFICATION          34299 non-null  object
 5   USE_CASE                34299 non-null  object
 6   ORGANIZATION            34299 non-null  object
 7   STATUS                  34299 non-null  int64
 8   INCOME_AMT              34299 non-null  object
 9   SPECIAL_CONSIDERATIONS  34299 non-null  object
 10  ASK_AMT                 34299 non-null  int64
 11  IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(4), object(8)
memory usage: 3.1+ MB

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
columns_to_drop = ["EIN", "NAME"]
application_df = application_df.drop(columns = columns_to_drop)

# Verify
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column by using 'nunique()'.
print(application_df.nunique())

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df["APPLICATION_TYPE"].value_counts()
application_type_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value (i.e., 500) and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_type_counts[application_type_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df["CLASSIFICATION"].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_more_than_1 = classification_counts[classification_counts > 1]
print(classification_counts_more_than_1)
print(f"Length: {len(classification_counts_more_than_1)}")

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64
Length: 45

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_application_df = pd.get_dummies(application_df)
numeric_application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [ ]:
# # Split our preprocessed data into our features and target arrays #Refs: Module 21/day2/Act06-07
y = numeric_application_df["IS_SUCCESSFUL"].values
X = numeric_application_df.drop(columns="IS_SUCCESSFUL").values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, stratify=y)

In [ ]:
# Preprocess numerical data for neural network

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep learning neural network, i.e., the number of input features and hidden nodes for each layer.
number_input_features = X_train.shape[1]

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=number_input_features))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=50, activation="relu"))

# Third hidden layer
nn_model.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 50)                4050

 dense_2 (Dense)             (None, 30)                1530

 dense_3 (Dense)             (None, 1)                 31

=================================================================
Total params: 9131 (35.67 KB)
Trainable params: 9131 (35.67 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
import os
import keras
from keras.callbacks import ModelCheckpoint

# Create directory if it does not exist
if not os.path.exists('./Callbacks_Opt_1'):
    os.makedirs('./Callbacks_Opt_1')

# Create the checkpoint callback
checkpoint_callback = ModelCheckpoint(
    filepath="./Callbacks_Opt_1/model_weights_epoch_{epoch:02d}.weights.h5",
    save_weights_only=True,
    save_freq='epoch',
    period=5
)

In [ ]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100, callbacks=[checkpoint_callback])

Epoch 1/100
804/804 [==============================] - 5s 2ms/step - loss: 0.5700 - accuracy: 0.7201
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5557 - accuracy: 0.7281
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5527 - accuracy: 0.7295
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5515 - accuracy: 0.7304
Epoch 5/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5499 - accuracy: 0.7313
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5490 - accuracy: 0.7310
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5485 - accuracy: 0.7317
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5474 - accuracy: 0.7318
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5469 - accuracy: 0.7321
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5466 - accuracy: 0.7332
Epoch 11/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5464 - accuracy: 0.7323
Epoch 12/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5451 - accuracy: 0.7340
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7341
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7335
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7337
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7348
Epoch 17/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5436 - accuracy: 0.7346
Epoch 18/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5433 - accuracy: 0.7357
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7358
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7341
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5425 - accuracy: 0.7352
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7346
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5422 - accuracy: 0.7357
Epoch 24/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5419 - accuracy: 0.7370
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7352
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5415 - accuracy: 0.7357
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.7358
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7350
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7364
Epoch 30/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5406 - accuracy: 0.7366
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5402 - accuracy: 0.7366
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7348
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7371
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7371
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7363
Epoch 36/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5395 - accuracy: 0.7372
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5394 - accuracy: 0.7373
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7367
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7379
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7370
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7376
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5385 - accuracy: 0.7378
Epoch 43/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5381 - accuracy: 0.7366
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7372
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7372
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7382
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7378
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7380
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7384
Epoch 50/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5371 - accuracy: 0.7376
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7389
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7380
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5367 - accuracy: 0.7386
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7381
Epoch 55/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5370 - accuracy: 0.7390
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7391
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7386
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7380
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7378
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7388
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7391
Epoch 62/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5358 - accuracy: 0.7392
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7395
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7386
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7388
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7388
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7391
Epoch 68/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5355 - accuracy: 0.7395
Epoch 69/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5350 - accuracy: 0.7388
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7401
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7392
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7385
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7400
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5343 - accuracy: 0.7397
Epoch 75/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5347 - accuracy: 0.7394
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7388
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7387
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7399
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7399
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7397
Epoch 81/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5344 - accuracy: 0.7393
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5346 - accuracy: 0.7400
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7397
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7390
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7400
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7399
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7400
Epoch 88/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5338 - accuracy: 0.7409
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5342 - accuracy: 0.7400
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7390
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7406
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7401
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7401
Epoch 94/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5336 - accuracy: 0.7399
Epoch 95/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5345 - accuracy: 0.7398
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7397
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7402
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7403
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7402
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7399

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5681 - accuracy: 0.7307 - 525ms/epoch - 2ms/step
Loss: 0.5681383013725281, Accuracy: 0.7307288646697998

In [ ]:
# Export our model to HDF5 file
nn_model.save("./Callbacks_Opt_1/AlphabetSoupCharity_Optimization_1.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.