<a href="https://colab.research.google.com/github/hatkiet/deep-learning-challenge/blob/main/AlphabetSoupCharity_Optimization_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
application_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EIN                     34299 non-null  int64
 1   NAME                    34299 non-null  object
 2   APPLICATION_TYPE        34299 non-null  object
 3   AFFILIATION             34299 non-null  object
 4   CLASSIFICATION          34299 non-null  object
 5   USE_CASE                34299 non-null  object
 6   ORGANIZATION            34299 non-null  object
 7   STATUS                  34299 non-null  int64
 8   INCOME_AMT              34299 non-null  object
 9   SPECIAL_CONSIDERATIONS  34299 non-null  object
 10  ASK_AMT                 34299 non-null  int64
 11  IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(4), object(8)
memory usage: 3.1+ MB

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
columns_to_drop = ["EIN"]
application_df = application_df.drop(columns = columns_to_drop)

# Verify
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column by using 'nunique()'.
print(application_df.nunique())

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [ ]:
# Look at NAME value counts to identify and replace with "Other"
name_counts = application_df["NAME"].value_counts()
name_counts

NAME
PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: count, Length: 19568, dtype: int64

In [ ]:
# Choose a cutoff value (i.e., 500) and create a list of names to be replaced
# use the variable name `name_to_replace`
name_to_replace = list(name_counts[name_counts < 5].index)

# Replace in dataframe
for name in name_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure replacement was successful
application_df['NAME'].value_counts()

NAME
Other                                                                19803
PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
                                                                     ...
GUILDS OF THE SANTA FE OPERA INC                                         5
FAMILY MOTOR COACH ASSOCIATION                                           5
JAMESTOWN SOCIETY                                                        5
MOST WORSHIPFUL PRINCE HALL GRAND LODGE OF FREE & ACCEPTED MASONS        5
PTA HAWAII CONGRESS                                                      5
Name: count, Length: 403, dtype: int64

In [ ]:
# Again, determine the number of unique values in each column by using 'nunique()'.
print(application_df.nunique())

NAME                       403
APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df["APPLICATION_TYPE"].value_counts()
application_type_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value (i.e., 500) and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_type_counts[application_type_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df["CLASSIFICATION"].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_more_than_1 = classification_counts[classification_counts > 1]
print(classification_counts_more_than_1)
print(f"Length: {len(classification_counts_more_than_1)}")

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64
Length: 45

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_application_df = pd.get_dummies(application_df)
numeric_application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_ACTS MINISTRY,NAME_ACTS MISSIONS,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [ ]:
# # Split our preprocessed data into our features and target arrays #Refs: Module 21/day2/Act06-07
y = numeric_application_df["IS_SUCCESSFUL"].values
X = numeric_application_df.drop(columns="IS_SUCCESSFUL").values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, stratify=y)

In [ ]:
X_train.shape[1]

446

In [ ]:
# Preprocess numerical data for neural network

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep learning neural network, i.e., the number of input features and hidden nodes for each layer.
number_input_features = X_train.shape[1]

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=50, activation="relu", input_dim=number_input_features))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=80, activation="relu"))

# Third hidden layer
nn_model.add(tf.keras.layers.Dense(units=50, activation="relu"))


# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 50)                22350

 dense_1 (Dense)             (None, 80)                4080

 dense_2 (Dense)             (None, 50)                4050

 dense_3 (Dense)             (None, 1)                 51

=================================================================
Total params: 30531 (119.26 KB)
Trainable params: 30531 (119.26 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
import os
import keras
from keras.callbacks import ModelCheckpoint

# Create directory if it does not exist
if not os.path.exists('./Callbacks_Opt_3'):
    os.makedirs('./Callbacks_Opt_3')

# Create the checkpoint callback
checkpoint_callback = ModelCheckpoint(
    filepath="./Callbacks_Opt_3/model_weights_epoch_{epoch:02d}.weights.h5",
    save_weights_only=True,
    save_freq='epoch',
    period=5
)

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

In [ ]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100, callbacks=[checkpoint_callback])

Epoch 1/100
804/804 [==============================] - 2s 3ms/step - loss: 0.3982 - accuracy: 0.8084
Epoch 2/100
804/804 [==============================] - 3s 3ms/step - loss: 0.3974 - accuracy: 0.8086
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3991 - accuracy: 0.8087
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3974 - accuracy: 0.8087
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3977 - accuracy: 0.8103
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3975 - accuracy: 0.8090
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4000 - accuracy: 0.8085
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3980 - accuracy: 0.8087
Epoch 9/100
804/804 [==============================] - 3s 4ms/step - loss: 0.3974 - accuracy: 0.8094
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3977 - accuracy: 0.8090
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3969 - accuracy: 0.8092
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3973 - accuracy: 0.8095
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3979 - accuracy: 0.8087
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3970 - accuracy: 0.8094
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.3968 - accuracy: 0.8092
Epoch 16/100
804/804 [==============================] - 3s 3ms/step - loss: 0.3982 - accuracy: 0.8090
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3967 - accuracy: 0.8090
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3976 - accuracy: 0.8096
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3971 - accuracy: 0.8091
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3966 - accuracy: 0.8101
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3965 - accuracy: 0.8097
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.3964 - accuracy: 0.8094
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.3981 - accuracy: 0.8094
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3971 - accuracy: 0.8092
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3967 - accuracy: 0.8086
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3962 - accuracy: 0.8090
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3973 - accuracy: 0.8088
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3972 - accuracy: 0.8098
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.3967 - accuracy: 0.8091
Epoch 30/100
804/804 [==============================] - 3s 3ms/step - loss: 0.3962 - accuracy: 0.8097
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8092
Epoch 32/100
804/804 [==============================] - 3s 4ms/step - loss: 0.3962 - accuracy: 0.8094
Epoch 33/100
804/804 [==============================] - 4s 5ms/step - loss: 0.3969 - accuracy: 0.8098
Epoch 34/100
804/804 [==============================] - 6s 7ms/step - loss: 0.3968 - accuracy: 0.8099
Epoch 35/100
804/804 [==============================] - 5s 6ms/step - loss: 0.3969 - accuracy: 0.8091
Epoch 36/100
804/804 [==============================] - 3s 4ms/step - loss: 0.3957 - accuracy: 0.8100
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3974 - accuracy: 0.8087
Epoch 38/100
804/804 [==============================] - 3s 4ms/step - loss: 0.3959 - accuracy: 0.8096
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3969 - accuracy: 0.8092
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3972 - accuracy: 0.8097
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3964 - accuracy: 0.8098
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3961 - accuracy: 0.8090
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3961 - accuracy: 0.8092
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3958 - accuracy: 0.8097
Epoch 45/100
804/804 [==============================] - 3s 4ms/step - loss: 0.3971 - accuracy: 0.8092
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3972 - accuracy: 0.8088
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3988 - accuracy: 0.8090
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3968 - accuracy: 0.8094
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3962 - accuracy: 0.8095
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3958 - accuracy: 0.8095
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.3954 - accuracy: 0.8096
Epoch 52/100
804/804 [==============================] - 3s 3ms/step - loss: 0.3959 - accuracy: 0.8087
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3962 - accuracy: 0.8091
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3971 - accuracy: 0.8100
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3959 - accuracy: 0.8097
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3964 - accuracy: 0.8098
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3957 - accuracy: 0.8099
Epoch 58/100
804/804 [==============================] - 3s 3ms/step - loss: 0.3965 - accuracy: 0.8093
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.3968 - accuracy: 0.8101
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3954 - accuracy: 0.8094
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3954 - accuracy: 0.8092
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3959 - accuracy: 0.8099
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3963 - accuracy: 0.8099
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3962 - accuracy: 0.8102
Epoch 65/100
804/804 [==============================] - 3s 4ms/step - loss: 0.3954 - accuracy: 0.8095
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3963 - accuracy: 0.8099
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3957 - accuracy: 0.8092
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3953 - accuracy: 0.8102
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3955 - accuracy: 0.8097
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3972 - accuracy: 0.8095
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.3968 - accuracy: 0.8094
Epoch 72/100
804/804 [==============================] - 3s 3ms/step - loss: 0.3953 - accuracy: 0.8092
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3959 - accuracy: 0.8098
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3949 - accuracy: 0.8104
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3958 - accuracy: 0.8099
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3963 - accuracy: 0.8099
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3958 - accuracy: 0.8098
Epoch 78/100
804/804 [==============================] - 4s 6ms/step - loss: 0.3965 - accuracy: 0.8101
Epoch 79/100
804/804 [==============================] - 3s 4ms/step - loss: 0.3956 - accuracy: 0.8101
Epoch 80/100
804/804 [==============================] - 3s 3ms/step - loss: 0.3949 - accuracy: 0.8097
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3954 - accuracy: 0.8099
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3954 - accuracy: 0.8096
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3960 - accuracy: 0.8101
Epoch 84/100
804/804 [==============================] - 3s 4ms/step - loss: 0.3957 - accuracy: 0.8095
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3949 - accuracy: 0.8108
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3955 - accuracy: 0.8105
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.3950 - accuracy: 0.8102
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.3955 - accuracy: 0.8092
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.3962 - accuracy: 0.8098
Epoch 90/100
613/804 [=====================>........] - ETA: 0s - loss: 0.3936 - accuracy: 0.8114

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5374 - accuracy: 0.7958 - 569ms/epoch - 2ms/step
Loss: 0.5374132990837097, Accuracy: 0.7958017587661743

In [ ]:
# Export our model to HDF5 file
nn_model.save("./Callbacks_Opt_3/AlphabetSoupCharity_Optimization_3.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(